merging in upnpfs

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -793,6 +793,8 @@ ac_includes_default="\
 ac_subst_vars='LTLIBOBJS
 ENABLE_OPTIONAL_FALSE
 ENABLE_OPTIONAL_TRUE
+ENABLE_UPNPFS_FALSE
+ENABLE_UPNPFS_TRUE
 ENABLE_MEDIASERVER_FALSE
 ENABLE_MEDIASERVER_TRUE
 ENABLE_CONTROLLER_FALSE
@@ -801,10 +803,13 @@ DARWIN_FALSE
 DARWIN_TRUE
 LINUX_FALSE
 LINUX_TRUE
-pkgconfigdir
+LIBFUSE_LIBS
+LIBFUSE_CFLAGS
+PKG_CONFIG
 MAGIC_LIBS
 MAGIC_CFLAGS
 READLINE_LIBS
+pkgconfigdir
 LIBOBJS
 CHMOD
 LIBTOOL
@@ -933,6 +938,7 @@ with_pic
 with_tags
 with_pkgconfigdir
 enable_controller
+enable_upnpfs
 enable_mediaserver
 enable_optional
 '
@@ -950,7 +956,10 @@ CXXFLAGS
 CCC
 CXXCPP
 F77
-FFLAGS'
+FFLAGS
+PKG_CONFIG
+LIBFUSE_CFLAGS
+LIBFUSE_LIBS'
 
 
 # Initialize some variables set by options.
@@ -1592,6 +1601,7 @@ Optional Features:
                           optimize for fast installation [default=yes]
   --disable-libtool-lock  avoid locking (might break parallel builds)
   --disable-controller    disable controller application [default=yes]
+  --disable-upnpfs        disable upnpfs controller [default=yes]
   --disable-mediaserver   disable mediaserver application [default=yes]
   --enable-optional       enable optional upnp av functions [default=no]
 
@@ -1618,6 +1628,11 @@ Some influential environment variables:
   CXXCPP      C++ preprocessor
   F77         Fortran 77 compiler command
   FFLAGS      Fortran 77 compiler flags
+  PKG_CONFIG  path to pkg-config utility
+  LIBFUSE_CFLAGS
+              C compiler flags for LIBFUSE, overriding pkg-config
+  LIBFUSE_LIBS
+              linker flags for LIBFUSE, overriding pkg-config
 
 Use these variables to override the choices made by `configure' or to help
 it to find libraries and programs with nonstandard names/locations.
@@ -6648,7 +6663,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 6651 "configure"' > conftest.$ac_ext
+  echo '#line 6666 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -8765,11 +8780,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8768: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8783: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8772: \$? = $ac_status" >&5
+   echo "$as_me:8787: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -9055,11 +9070,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9058: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9073: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:9062: \$? = $ac_status" >&5
+   echo "$as_me:9077: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -9159,11 +9174,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9162: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9177: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:9166: \$? = $ac_status" >&5
+   echo "$as_me:9181: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -11559,7 +11574,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 11562 "configure"
+#line 11577 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11659,7 +11674,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 11662 "configure"
+#line 11677 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -14068,11 +14083,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14071: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14086: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14075: \$? = $ac_status" >&5
+   echo "$as_me:14090: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14172,11 +14187,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14175: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14190: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14179: \$? = $ac_status" >&5
+   echo "$as_me:14194: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15755,11 +15770,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15758: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15773: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15762: \$? = $ac_status" >&5
+   echo "$as_me:15777: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -15859,11 +15874,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15862: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15877: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15866: \$? = $ac_status" >&5
+   echo "$as_me:15881: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18074,11 +18089,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18077: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18092: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:18081: \$? = $ac_status" >&5
+   echo "$as_me:18096: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -18364,11 +18379,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18367: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18382: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:18371: \$? = $ac_status" >&5
+   echo "$as_me:18386: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -18468,11 +18483,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18471: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18486: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:18475: \$? = $ac_status" >&5
+   echo "$as_me:18490: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -22773,6 +22788,19 @@ CFLAGS="$CFLAGS -Wall -Werror"
 # dependencies
 #
 
+# - pkgconfig
+
+
+# Check whether --with-pkgconfigdir was given.
+if test "${with_pkgconfigdir+set}" = set; then
+  withval=$with_pkgconfigdir; pkgconfigdir=$withval
+else
+  pkgconfigdir='${libdir}/pkgconfig'
+fi
+
+
+
+
 # - readline
 
 
@@ -23488,14 +23516,237 @@ fi
 LIBS="$LIBS $MAGIC_LIBS"
 CFLAGS="$CFLAGS $MAGIC_CFLAGS"
 
+# - fuse
 
-# Check whether --with-pkgconfigdir was given.
-if test "${with_pkgconfigdir+set}" = set; then
-  withval=$with_pkgconfigdir; pkgconfigdir=$withval
+
+
+if test "x$ac_cv_env_PKG_CONFIG_set" != "xset"; then
+	if test -n "$ac_tool_prefix"; then
+  # Extract the first word of "${ac_tool_prefix}pkg-config", so it can be a program name with args.
+set dummy ${ac_tool_prefix}pkg-config; ac_word=$2
+{ $as_echo "$as_me:$LINENO: checking for $ac_word" >&5
+$as_echo_n "checking for $ac_word... " >&6; }
+if test "${ac_cv_path_PKG_CONFIG+set}" = set; then
+  $as_echo_n "(cached) " >&6
 else
-  pkgconfigdir='${libdir}/pkgconfig'
+  case $PKG_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_PKG_CONFIG="$PKG_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_PKG_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    $as_echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+PKG_CONFIG=$ac_cv_path_PKG_CONFIG
+if test -n "$PKG_CONFIG"; then
+  { $as_echo "$as_me:$LINENO: result: $PKG_CONFIG" >&5
+$as_echo "$PKG_CONFIG" >&6; }
+else
+  { $as_echo "$as_me:$LINENO: result: no" >&5
+$as_echo "no" >&6; }
 fi
 
+
+fi
+if test -z "$ac_cv_path_PKG_CONFIG"; then
+  ac_pt_PKG_CONFIG=$PKG_CONFIG
+  # Extract the first word of "pkg-config", so it can be a program name with args.
+set dummy pkg-config; ac_word=$2
+{ $as_echo "$as_me:$LINENO: checking for $ac_word" >&5
+$as_echo_n "checking for $ac_word... " >&6; }
+if test "${ac_cv_path_ac_pt_PKG_CONFIG+set}" = set; then
+  $as_echo_n "(cached) " >&6
+else
+  case $ac_pt_PKG_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_ac_pt_PKG_CONFIG="$ac_pt_PKG_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_ac_pt_PKG_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    $as_echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+ac_pt_PKG_CONFIG=$ac_cv_path_ac_pt_PKG_CONFIG
+if test -n "$ac_pt_PKG_CONFIG"; then
+  { $as_echo "$as_me:$LINENO: result: $ac_pt_PKG_CONFIG" >&5
+$as_echo "$ac_pt_PKG_CONFIG" >&6; }
+else
+  { $as_echo "$as_me:$LINENO: result: no" >&5
+$as_echo "no" >&6; }
+fi
+
+  if test "x$ac_pt_PKG_CONFIG" = x; then
+    PKG_CONFIG=""
+  else
+    case $cross_compiling:$ac_tool_warned in
+yes:)
+{ $as_echo "$as_me:$LINENO: WARNING: using cross tools not prefixed with host triplet" >&5
+$as_echo "$as_me: WARNING: using cross tools not prefixed with host triplet" >&2;}
+ac_tool_warned=yes ;;
+esac
+    PKG_CONFIG=$ac_pt_PKG_CONFIG
+  fi
+else
+  PKG_CONFIG="$ac_cv_path_PKG_CONFIG"
+fi
+
+fi
+if test -n "$PKG_CONFIG"; then
+	_pkg_min_version=0.9.0
+	{ $as_echo "$as_me:$LINENO: checking pkg-config is at least version $_pkg_min_version" >&5
+$as_echo_n "checking pkg-config is at least version $_pkg_min_version... " >&6; }
+	if $PKG_CONFIG --atleast-pkgconfig-version $_pkg_min_version; then
+		{ $as_echo "$as_me:$LINENO: result: yes" >&5
+$as_echo "yes" >&6; }
+	else
+		{ $as_echo "$as_me:$LINENO: result: no" >&5
+$as_echo "no" >&6; }
+		PKG_CONFIG=""
+	fi
+
+fi
+
+pkg_failed=no
+{ $as_echo "$as_me:$LINENO: checking for LIBFUSE" >&5
+$as_echo_n "checking for LIBFUSE... " >&6; }
+
+if test -n "$LIBFUSE_CFLAGS"; then
+    pkg_cv_LIBFUSE_CFLAGS="$LIBFUSE_CFLAGS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libfuse\"") >&5
+  ($PKG_CONFIG --exists --print-errors "libfuse") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_LIBFUSE_CFLAGS=`$PKG_CONFIG --cflags "libfuse" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+if test -n "$LIBFUSE_LIBS"; then
+    pkg_cv_LIBFUSE_LIBS="$LIBFUSE_LIBS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libfuse\"") >&5
+  ($PKG_CONFIG --exists --print-errors "libfuse") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_LIBFUSE_LIBS=`$PKG_CONFIG --libs "libfuse" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        LIBFUSE_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "libfuse" 2>&1`
+        else
+	        LIBFUSE_PKG_ERRORS=`$PKG_CONFIG --print-errors "libfuse" 2>&1`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$LIBFUSE_PKG_ERRORS" >&5
+
+	{ $as_echo "$as_me:$LINENO: result: no" >&5
+$as_echo "no" >&6; }
+                HAVE_LIBFUSE=no
+elif test $pkg_failed = untried; then
+	HAVE_LIBFUSE=no
+else
+	LIBFUSE_CFLAGS=$pkg_cv_LIBFUSE_CFLAGS
+	LIBFUSE_LIBS=$pkg_cv_LIBFUSE_LIBS
+        { $as_echo "$as_me:$LINENO: result: yes" >&5
+$as_echo "yes" >&6; }
+	HAVE_LIBFUSE=yes
+fi
+if test "$HAVE_LIBFUSE" = "yes"
+then
+	enable_libfuse=yes
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_LIBFUSE 1
+_ACEOF
+
+else
+	enable_libfuse=no
+fi
+
+{ $as_echo "$as_me:$LINENO: checking if FUSE on this system is too new for us" >&5
+$as_echo_n "checking if FUSE on this system is too new for us... " >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#define _FILE_OFFSET_BITS 64
+#define FUSE_USE_VERSION 27
+#include "fuse.h"
+#if FUSE_VERSION > 27
+fuse_version_yes
+#endif
+
+_ACEOF
+if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
+  $EGREP "fuse_version_yes" >/dev/null 2>&1; then
+
+cat >>confdefs.h <<\_ACEOF
+#define FUSE_USE_VERSION 27
+_ACEOF
+ { $as_echo "$as_me:$LINENO: result: yes" >&5
+$as_echo "yes" >&6; }
+else
+
+cat >>confdefs.h <<\_ACEOF
+#define FUSE_USE_VERSION FUSE_VERSION
+_ACEOF
+ { $as_echo "$as_me:$LINENO: result: no" >&5
+$as_echo "no" >&6; }
+fi
+rm -f conftest*
 
 
 #
@@ -23521,6 +23772,34 @@ else
 
 cat >>confdefs.h <<\_ACEOF
 #define ENABLE_CONTROLLER 1
+_ACEOF
+
+
+fi
+
+
+# Check whether --enable-upnpfs was given.
+if test "${enable_upnpfs+set}" = set; then
+  enableval=$enable_upnpfs; if test "$enableval" = "no" -o "$enable_libfuse" = "no"
+then
+	enable_upnpfs=no
+else
+if test "$enable_libfuse" = "yes"
+then
+	enable_upnpfs=yes
+
+cat >>confdefs.h <<\_ACEOF
+#define ENABLE_UPNPFS 1
+_ACEOF
+
+fi
+fi
+
+else
+  enable_upnpfs=yes
+
+cat >>confdefs.h <<\_ACEOF
+#define ENABLE_UPNPFS 1
 _ACEOF
 
 
@@ -23609,6 +23888,14 @@ else
   ENABLE_MEDIASERVER_FALSE=
 fi
 
+ if test "$enable_upnpfs" = "yes"; then
+  ENABLE_UPNPFS_TRUE=
+  ENABLE_UPNPFS_FALSE='#'
+else
+  ENABLE_UPNPFS_TRUE='#'
+  ENABLE_UPNPFS_FALSE=
+fi
+
 
  if test "$enable_optional" = "yes"; then
   ENABLE_OPTIONAL_TRUE=
@@ -23623,7 +23910,7 @@ fi
 # Create files
 #
 
-ac_config_files="$ac_config_files Makefile ixml/Makefile upnpd/Makefile upnpd/common/Makefile upnpd/common/upnp/Makefile upnpd/controller/Makefile upnpd/mediaserver/Makefile"
+ac_config_files="$ac_config_files Makefile ixml/Makefile upnpd/Makefile upnpd/common/Makefile upnpd/common/upnp/Makefile upnpd/controller/Makefile upnpd/mediaserver/Makefile upnpfs/Makefile"
 
 
 cat >confcache <<\_ACEOF
@@ -23783,6 +24070,13 @@ if test -z "${ENABLE_MEDIASERVER_TRUE}" && test -z "${ENABLE_MEDIASERVER_FALSE}"
   { { $as_echo "$as_me:$LINENO: error: conditional \"ENABLE_MEDIASERVER\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 $as_echo "$as_me: error: conditional \"ENABLE_MEDIASERVER\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${ENABLE_UPNPFS_TRUE}" && test -z "${ENABLE_UPNPFS_FALSE}"; then
+  { { $as_echo "$as_me:$LINENO: error: conditional \"ENABLE_UPNPFS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+$as_echo "$as_me: error: conditional \"ENABLE_UPNPFS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -24310,6 +24604,7 @@ do
     "upnpd/common/upnp/Makefile") CONFIG_FILES="$CONFIG_FILES upnpd/common/upnp/Makefile" ;;
     "upnpd/controller/Makefile") CONFIG_FILES="$CONFIG_FILES upnpd/controller/Makefile" ;;
     "upnpd/mediaserver/Makefile") CONFIG_FILES="$CONFIG_FILES upnpd/mediaserver/Makefile" ;;
+    "upnpfs/Makefile") CONFIG_FILES="$CONFIG_FILES upnpfs/Makefile" ;;
 
   *) { { $as_echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
 $as_echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
